name: Build and test

on:
  push:
    branches: [ master ]
    paths-ignore:
    - "**.nuspec"
    - "**/publish.yml"
    - "**/*.ps1"
    - "**/*.md"
    - "**/*.png"
    - "**/LICENSE"
    - "**/LICENSE.txt"
  pull_request:
    branches: [ master ]
    paths-ignore:
    - "**.nuspec"
    - "**/publish.yml"
    - "**/*.ps1"
    - "**/*.md"
    - "**/*.png"
    - "**/LICENSE"
    - "**/LICENSE.txt"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x        
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      env:
        TESTSECRET: ${{secrets.TESTSECRET}}        
        SQLCONNSTRING: ${{secrets.SQLCONNSTRING}} 
