name: Build and test .Net Core app

on:
  push:
    branches: [ master ]
    paths-ignore:
    - "README.md"
    - "LICENSE"
    - ".gitattributes"
    - ".gitignore"
    - ".github/**"
    - ".vscode/**"
  pull_request:
    branches: [ master ]
    paths-ignore:
    - "README.md"
    - "LICENSE"
    - ".gitattributes"
    - ".gitignore"
    - ".github/**"
    - ".vscode/**"    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        TESTSECRET: ${{secrets.TESTSECRET}}        
        SQLCONNSTRING: ${{secrets.SQLCONNSTRING}} 
