name: Build and test .Net Core app

on:
  push:
    branches: [ master ]
    paths-ignore:
    - "README.md"
    - "LICENSE"
    - ".gitattributes"
    - ".gitignore"
    #- ".github/**"
    - ".vscode/**"
  pull_request:
    branches: [ master ]
    paths-ignore:
    - "README.md"
    - "LICENSE"
    - ".gitattributes"
    - ".gitignore"
    #- ".github/**"
    - ".vscode/**"    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: ${{secrets.NUGET_API_KEY}}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x        
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      env:
        TESTSECRET: ${{secrets.TESTSECRET}}        
        SQLCONNSTRING: ${{secrets.SQLCONNSTRING}} 

    - name: Publish
      run: dotnet publish Zoro/Zoro.csproj --configuration Release --runtime win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained true
        
    - name: Pack
      run: nuget pack Zoro.Processor/Dandraka.Zoro.nuspec
      
    - name: Publish
      run: nuget push Dandraka.Zoro.*.nupkg -Source https://www.nuget.org/api/v2/package
