name: Build .Net 4.6.1 app
 
on:
  push:
    branches: [ dotnet-461 ]
  pull_request:
    branches: [ dotnet-461 ]
 
jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore Zoro.sln

      - name: Build Solution
        run: |
          msbuild.exe Zoro.sln /p:platform="Any CPU" /p:configuration="Release"

# disabled tests until we fix the paths
#      - name: Run Tests
#        run: vstest.console.exe Zoro.Tests\bin\Release\Zoro.Tests.dll
