name: Build test and publish

on:
  workflow_dispatch:
  #push:
  #  branches: [ master ]
  #  paths:
  #  - "**.nuspec"
  #pull_request:
  #  branches: [ master ]
  #  paths:
  #  - "**.nuspec"

permissions:
  contents: write  # required to create the tag

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x        
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      env:
        TESTSECRET: ${{secrets.TESTSECRET}}        
        SQLCONNSTRING: ${{secrets.SQLCONNSTRING}} 

    - name: Generate executable (win)
      run: dotnet publish Zoro/Zoro.csproj --configuration Release --runtime win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained true

    - name: Generate executable (linux)
      run: dotnet publish Zoro/Zoro.csproj --configuration Release --runtime linux-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained true              

    - name: Pack
      # Use dotnet pack instead of nuget pack
      # run: dotnet pack Zoro.Processor/Zoro.Processor.csproj --configuration Release --output ./nupkgs
      run: dotnet pack Zoro.Processor/Dandraka.Zoro.nuspec

    # for troubleshooting only
    #- name: Debug API Key
    #  run: |
    #    KEY="${{ secrets.NUGET_API_KEY }}"
    #    echo "Key prefix: ${KEY:0:3}..."      

    #- name: Publish
    #  # Use dotnet nuget push instead of nuget push
    #  run: dotnet nuget push ./*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json    

    - name: Create Git Tag
      shell: pwsh
      run: |
        # 1. Read the version from your nuspec file
        [xml]$xml = Get-Content -Path "Zoro.Processor/Dandraka.Zoro.nuspec"
        $version = $xml.package.metadata.version
        $tagName = "v$version"
        
        Write-Host "Creating tag: $tagName"

        # 2. Configure Git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # 3. Create and push the tag
        # Use --force if you want to be able to overwrite the tag, 
        # otherwise remove it to fail if the tag already exists.
        git tag $tagName
        git push origin $tagName      